### ISSUE TITLE
When will the code be available?

### ISSUE THREAD

**Issue by nimakondori** [JunweiLiang/MultiTrain#1]
Are there any updates on when the code will be shared? 

Thanks a lot for the nice paper

**Comment by JunweiLiang** [comment]
Sorry for the super-late delay. The paper's work was initially trained using 128 A100 GPUs. Since I'm no longer with the big company, I am reproducing the results using much smaller machines like 4x3090 and more efficient recipes. Will release the code and model no later than mid-July!

**Comment by nimakondori** [comment]
Thanks for the update and looking forward to seeing the new version of the code.
