### ISSUE TITLE
How to replace the backbone?

### ISSUE THREAD

**Issue by nk-dev0** [JunweiLiang/MultiTrain#2]
I've been looking through the code and trying to determine how easy it is to use a completely different transformer backbone, but it appears a lot of the paper-specific methods are worked directly into the MViTV2 model. Any help would be greatly appreciated.

**Comment by JunweiLiang** [comment]
I suggest working on [`video_model_builder.py`](https://github.com/JunweiLiang/MultiTrain/blob/main/slowfast/models/video_model_builder.py#L34) to replace the MViT model with yours. Or you could use the [loss part](https://github.com/JunweiLiang/MultiTrain/blob/main/slowfast/models/losses.py#L137) in your model.

**Comment by nk-dev0** [comment]
Thanks for the quick reply. The main pieces I need to take from MViT are the multiple classification heads with associated losses, but is there anything else that would pop out to you? 

Is it as simple as just applying the inf and cross proj losses to my model (once I add dataset-specific MLP heads)?

**Comment by JunweiLiang** [comment]
> Thanks for the quick reply. The main pieces I need to take from MViT are the multiple classification heads with associated losses, but is there anything else that would pop out to you?

I suggest you try adding the inf loss first. This is as simple as adding an `emb` interface from your model and computing the loss based on that. See [here](https://github.com/JunweiLiang/MultiTrain/blob/main/tools/train_net.py#L153)

The multi-head is defined in [`head_helper.py`](https://github.com/JunweiLiang/MultiTrain/blob/main/tools/train_net.py#L153), which is a bit more complex.

> Is it as simple as just applying the inf and cross proj losses to my model (once I add dataset-specific MLP heads)?

Yes.
